#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_packet="0.0.1"
  jq -n --arg packet "$ver_packet" '{packet: $packet}'
}

version "$@"
